# Generated by Django 3.2.5 on 2021-09-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpcomingBurials',
        ),
    ]
