# Generated by Django 3.2.5 on 2021-09-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/%Y/%m/%d'),
        ),
    ]
