# Generated by Django 3.2.5 on 2021-09-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_auto_20210924_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], default='Unpaid', max_length=15),
        ),
    ]
