# Generated by Django 3.2.5 on 2021-09-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={},
        ),
    ]
